[package]
name = "gizmo3d"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cpal = "0.15.2"
physx = "0.19.0"
pyo3 = "0.20.0"
wgpu = "0.18.0"
